version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: personal_info_manager
      POSTGRES_USER: dorsum
      POSTGRES_PASSWORD: secureP@ssw0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
